# Configuration file for the Strava Analysis Tool.

[paths]
strava_tokens_file = 'tokens.txt'
activity_data_file = 'data/strava_activities.json'
geo_data_file = 'data/strava_activities.geojson'

[data]
reverse_geocoding = false #true
update_existing_activities = true

[[data.description_tags]]
tag_name = "Type:"
column_name = "activity_subtype"
activity_types = ["BackcountrySki", "RockClimbing", "Kitesurf"]

# [mapbox]
# tileset_name = 'YOUR_NAME.StravaGeoData'
# tileset_zoom_level = 16

[plots]
plot_colour_palette = "Dark2"
heatmap_colour_palette = "viridis"
heatmap_column_wrap = 5
